server:
  port: 13801

spring:
  application:
    name: config-server
  profiles:
    active: native # 加载本地配置
  cloud:
    config:
      server:
        native:
          # 不指定路径的话，默认搜索 resources 目录
          search-locations: /home/master/web/config/
          #search-locations: C:/openspace/springcloud-config-server/config/

eureka:
  instance:
    hostname: Slave1
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
    lease-renewal-interval-in-seconds: 15
    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    # 默认为90秒
    # 如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
    # 如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
    # 该值至少应该大于 leaseRenewalIntervalInSeconds
    lease-expiration-duration-in-seconds: 45
  client:
    serviceUrl:
      defaultZone: http://Slave1:9527/eureka/,http://Slave2:9527/eureka/,http://Slave3:9527/eureka/
